interactions:
- request:
    body: '{"dataSourceType": "HttpRequest", "dataFeedName": "httprequestfeedgetasync66241a8b",
      "granularityName": "Daily", "metrics": [{"metricName": "cost"}, {"metricName":
      "revenue"}], "dimension": [{"dimensionName": "category"}, {"dimensionName":
      "city"}], "dataStartFrom": "2019-10-01T00:00:00.000Z", "startOffsetInSeconds":
      0, "maxConcurrency": -1, "minRetryIntervalInSeconds": -1, "stopRetryAfterInSeconds":
      -1, "dataSourceParameter": {"url": "connectionstring", "httpMethod": "GET"}}'
    headers:
      Accept:
      - application/json
      Content-Length:
      - '559'
      Content-Type:
      - application/json
      User-Agent:
      - azsdk-python-ai-metricsadvisor/1.0.0b4 Python/3.8.6 (Windows-10-10.0.19041-SP0)
    method: POST
    uri: https://js-metrics-advisor.cognitiveservices.azure.com/metricsadvisor/v1.0/dataFeeds
  response:
    body:
      string: '{"code":"ERROR_INVALID_DATA_SOURCE_TYPE","message":"This is a invalid
        data source type."}'
    headers:
      apim-request-id: ea2a69d1-14af-4889-985d-1379ddfb7d3a
      content-length: '89'
      content-type: application/json; charset=utf-8
      date: Wed, 19 May 2021 22:52:44 GMT
      strict-transport-security: max-age=31536000; includeSubDomains; preload
      x-content-type-options: nosniff
      x-envoy-upstream-service-time: '153'
      x-request-id: ea2a69d1-14af-4889-985d-1379ddfb7d3a
    status:
      code: 400
      message: Bad Request
    url: https://js-metrics-advisor.cognitiveservices.azure.com//metricsadvisor/v1.0/dataFeeds
version: 1
